// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdSYYRHhRBO0wwTEyvCZUZYOC7-740iQA',
    appId: '1:622000478450:web:8826bb4830cc20c40dd86b',
    messagingSenderId: '622000478450',
    projectId: 'rsvp-4ee51',
    authDomain: 'rsvp-4ee51.firebaseapp.com',
    storageBucket: 'rsvp-4ee51.appspot.com',
    measurementId: 'G-GEH6H0B9B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVS3QNqwi73K78twfECJygDS6DYsExiII',
    appId: '1:622000478450:android:18ea4fe426f0ba6a0dd86b',
    messagingSenderId: '622000478450',
    projectId: 'rsvp-4ee51',
    storageBucket: 'rsvp-4ee51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT2iDOCgl320MZrLsAd5nyiat6dX28168',
    appId: '1:622000478450:ios:abb1da418a3e16020dd86b',
    messagingSenderId: '622000478450',
    projectId: 'rsvp-4ee51',
    storageBucket: 'rsvp-4ee51.appspot.com',
    iosBundleId: 'com.example.rsvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT2iDOCgl320MZrLsAd5nyiat6dX28168',
    appId: '1:622000478450:ios:abb1da418a3e16020dd86b',
    messagingSenderId: '622000478450',
    projectId: 'rsvp-4ee51',
    storageBucket: 'rsvp-4ee51.appspot.com',
    iosBundleId: 'com.example.rsvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdSYYRHhRBO0wwTEyvCZUZYOC7-740iQA',
    appId: '1:622000478450:web:dbc8b2d211d6803c0dd86b',
    messagingSenderId: '622000478450',
    projectId: 'rsvp-4ee51',
    authDomain: 'rsvp-4ee51.firebaseapp.com',
    storageBucket: 'rsvp-4ee51.appspot.com',
    measurementId: 'G-6B6S3XEVEN',
  );
}
